### ISSUE TITLE
Add Rectangle app for window management

### ISSUE THREAD

**Issue by architchandra** [dkhamsing/open-source-ios-apps#1021]
[Rectangle](https://rectangleapp.com/) seems to be [open source](https://github.com/rxhanson/Rectangle). Should be a added to the list, right?

**Comment by dkhamsing** [comment]
This list is for iOS apps. Thanks though.

**Comment by architchandra** [comment]
My bad. Should have been more careful while reading.

**Comment by dkhamsing** [comment]
No worries
