### ISSUE TITLE
Add communication apps

### ISSUE THREAD

**Issue by itsnotsaved** [dkhamsing/open-source-ios-apps#1064]
- Zulip - Chat for distributed teams
https://zulip.com/apps/

- Session https://github.com/oxen-io/session-ios

- NextCloud Talk https://nextcloud.com/talk/

- Twake - https://twake.app/

- Status - https://status.im/

**Comment by dkhamsing** [comment]
- [ ] Zulip  
- [x] Session 
- [ ] NextCloud Talk 
- [ ] Twake 
- [ ] Status

**Comment by dkhamsing** [comment]
Thank you!
