### ISSUE TITLE
open source risk clone

### ISSUE THREAD

**Issue by sdyura** [dkhamsing/open-source-ios-apps#1083]
hi
maybe you want to make a new section for the MOE framework in games,
This game uses Multi-OS-Engine (Java on iOS) framework: https://multi-os-engine.org/

{
  "title": "risk clone - Domination",
  "category-ids": ["game", "moe"],
  "description": "Clone of the classic board game Risk",
  "source": "https://sf.net/p/domination/code/HEAD/tree/Domination/",
  "homepage": "http://risk.sf.net",
  "itunes": "https://apps.apple.com/app/id1602913079",		
  "license": "gpl-3.0",
  "lang": "java",     
  "stars": ?,     
  "tags": ["java"],
  "screenshots": ["http://domination.sf.net/screenshots/ss_tegmap.png"],
  "date_added": "Jul 26 2022",
  "suggested_by": "@sdyura"
}

**Comment by dkhamsing** [comment]
Thx!
