### ISSUE TITLE
submit two iOS App

### ISSUE THREAD

**Issue by coderyi** [dkhamsing/open-source-ios-apps#120]
1.ElevenPlayer
https://github.com/coderyi/Eleven

Eleven Player is a simple powerful video player.use ffmpeg. 

2.Mume

https://github.com/coderyi/Mume

MumeFM is a music player,Mume is a douban FM 3rd client for iOS.

**Comment by dkhamsing** [comment]
Thanks, will add em asap

**Comment by coderyi** [comment]
Thank you
