### ISSUE TITLE
Remove Frame Grabber, no longer open source

### ISSUE THREAD

**Issue by cewatts** [dkhamsing/open-source-ios-apps#1268]
Remove Frame Grabber, it has been sold, paywalled, source closed.

Old code still available, but not what's on App Store:
https://github.com/arthurhammer/FrameGrabber

The last open-source version published, 1.4.1, had appExtVrsId 857274295.

` As of June 2023, Frame Grabber has been acquired and is published by its new owner. This repo remains open-source as it has since day one. It contains the code up to the latest version I published myself, 1.4.1.
`

https://apps.apple.com/us/app/frame-grabber/id1434703541

**Comment by dkhamsing** [comment]
Thx, I'll take care of it
