### ISSUE TITLE
Kotlin app should not be in this list 

### ISSUE THREAD

**Issue by alokc83** [dkhamsing/open-source-ios-apps#1304]
[LivescoreApp using Sports API](https://github.com/gideonrotich/LivescoreApp)
[Screenshot 1](https://raw.githubusercontent.com/gideonrotich/LivescoreApp/master/screenshots/one.png)
2022 kotlin
☆76

**Comment by dkhamsing** [comment]
Removed ebe38395dcc61c354440d105cb25b7e75a12a354
