### ISSUE TITLE
iGit is not available on App store

### ISSUE THREAD

**Issue by akshaybharwani** [dkhamsing/open-source-ios-apps#1360]
Under the category [Github](https://github.com/dkhamsing/open-source-ios-apps?tab=readme-ov-file#github), the [iGit](https://github.com/git-up/GitUp?tab=readme-ov-file#complete-example-4-igit) app is just a test app and not available on App Store.

Using it would require building the [app](https://github.com/git-up/GitUp/tree/master/Examples/iGit) on Mac.

I don't think it should exist here.

**Comment by dkhamsing** [comment]
What you say is correct. Currently iGit is on the main list but not the App Store list
https://github.com/dkhamsing/open-source-ios-apps/blob/master/APPSTORE.md

It is currently on the main list as an example to connect go GitHub - seems ok

| [iGit](https://github.com/git-up/GitUp/blob/master/Examples/iGit) is a test iOS app that simply uses GitUpKit to clone a GitHub repo and perform a commit.

```
{
      "title": "iGit",
      "description": "Uses GitUpKit to clone a GitHub repo and perform a commit",
      "category-ids": [
        "github"
      ],
      "tags": [
        "objc"
      ],
      "license": "gpl-3.0",
      "source": "https://github.com/git-up/GitUp",
      "stars": 11134,
      "date_added": "May 8 2020",
      "suggested_by": "@dkhamsing",
      "updated": "2023-10-26 06:38:07 UTC"
    },
```
