### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#141]
- [ ] https://github.com/JensRavens/ReactiveKitten
- [ ] https://github.com/mergesort/Suburban
- [ ] https://github.com/student-t/ChessStudio
- [x] https://github.com/l800891/Sakura-Fly
- [ ] https://github.com/KeyCoApp/KeyCo :large_orange_diamond: 
- [ ] https://github.com/lojals/QRGen :large_orange_diamond: 
- [ ] https://github.com/lojals/hugeCT Currency converter :large_orange_diamond: 
- [ ] https://github.com/athiercelin/Simplistic
- [ ] https://github.com/matthewpalmer/Dictum
- [ ] https://github.com/flexih/Cafe
* [ ] https://github.com/pieterclaerhout/Arthur
* [ ] https://github.com/pieterclaerhout/Rachel
- [ ] https://github.com/zadr/Communique
- [ ] https://github.com/zadr/8mph
- [ ] https://github.com/rpowelll/LobsterApp
- [ ] https://github.com/jefferyleo/f.lux
- [ ] https://github.com/neonichu/EmojiFireplace tv os :fire: 
- [ ] https://github.com/Buglife/Buglife-iOS
- [ ] https://github.com/robbiehanson/AlarmClock
- [ ] https://github.com/ReactKit/ReactKitCalculator
- [ ] https://github.com/jonnybegood123/MedKeeper
- [ ] https://github.com/sonsongithub/reddift
- [ ] https://github.com/KinveyApps ... 
- [ ] https://github.com/lucasqiu/Adler-Mobile-App
- [ ] https://github.com/SlayterDev/DogeWallet
- [ ] https://github.com/mxcl/SelfieAssist
- [ ] https://github.com/mxcl/Kissogram
- [ ] https://github.com/e-mission/e-mission-phone
- [ ] https://github.com/NatashaTheRobot/RussianAlphabetForKids
- [ ] https://github.com/pietbrauer/wildcats
- [ ] https://github.com/andreamazz/Gitorade 1
- [ ] https://github.com/danylokostyshyn/AfishaLviv-iOS
- [ ] https://github.com/danylokostyshyn/FS-Player
- [ ] https://github.com/iOSBeginner/SleepTracker Record and improve your sleep 🇨🇳
- [ ] https://github.com/AdnanZahid/Math-Quest-iOS
- [ ] https://github.com/thomasdegry/Facebook-Pop-Introduction

# game
- [ ] https://github.com/jenduf/SwiftFanorona
- [ ] https://github.com/jamiely/ios-balloon-burst 8 
- [ ] https://github.com/Mav3r1ck/Tripletz 6
- [ ] https://github.com/redcirclegame/1w-flappy 
- [ ] https://github.com/gamechina/GoldenWar

# :smile: 
- [ ] [Coin Tracker](https://github.com/gregheo/CoinTracker): Cryptocurrency coin tracker :large_orange_diamond: 
- [ ] Cepp: Find information on addresses 🔶 🇧🇷
  - https://github.com/filipealva/Cepp
  - https://itunes.apple.com/br/app/cepp-encontre-ceps/id942709971

**Comment by rob-miller** [comment]
Please add rTracker
https://github.com/rob-miller/rTracker
probably best under Health
Thanks!  Great list.
