### ISSUE TITLE
Remove the flags?

### ISSUE THREAD

**Issue by hkalexling** [dkhamsing/open-source-ios-apps#156]
It doesn't seem to be a good idea to allow contributors to include the national flags in the README file. This affect the readability and might encourage others to do so

**Comment by dkhamsing** [comment]
Hmm isn't it helpful to know a project is in Chinese only??

**Comment by hkalexling** [comment]
Oops nvm, I thought they were added to show developers' nationalities.

**Comment by dkhamsing** [comment]
Cool ok :smile:
