### ISSUE TITLE
Merge Apps 

### ISSUE THREAD

**Issue by Bautistax** [dkhamsing/open-source-ios-apps#16]
visitBCN
https://github.com/maurovc/visitBCN
https://itunes.apple.com/us/app/visitbcn/id904676442?l=es&ls=1&mt=8

a menjar
https://github.com/maurovc/aMenjar
https://itunes.apple.com/us/app/a-menjar!/id816473131?l=es&ls=1&mt=8

Color Blur
https://github.com/maurovc/ColorBlur
https://itunes.apple.com/us/app/id928863510

iGrades
https://github.com/maurovc/iGrades
https://itunes.apple.com/us/app/id816987574

**Comment by Bautistax** [comment]
Peggsite
https://github.com/jenduf/GenericSocialApp
https://itunes.apple.com/us/app/peggsite/id938445951?mt=8

**Comment by anthonymonori** [comment]
It would be really helpful if you would create a pull request instead of suggesting new ones as an issue.

**Comment by dkhamsing** [comment]
It's ok, all contributions are welcome :-)
