### ISSUE TITLE
Note for pay apps

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#19]
:moneybag: 
:star: 
:exclamation: 
:bomb: 
:warning: 
:zap:  this one ?
:small_red_triangle: 
:red_circle: 

- [ ] concurrency 
- [ ] jupp 
- [ ] vpn on
- [ ] round and split

**Comment by matteocrippa** [comment]
I'd vote for :moneybag:

**Comment by dkhamsing** [comment]
hehe thx
it's a bit strong :grin:

**Comment by dkhamsing** [comment]
Merged in #22
