### ISSUE TITLE
Consistent Format

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#267]
Right now there are two listing formats
- apps on app store
- apps not on app store

The list should be consistent and follow the format of apps on app store (link listed below, indented)

---

Before:

- [app not on app store](link): description

After:

- app not on app store: description
  - http://app-link.co

**Comment by dkhamsing** [comment]
Part of this update can move badges to its own line

Before:

- app name: description 🔶🔥
  - http://github.com/app
  - http://itunes-link.co

After:

- app name: description
  - 🔶🔥
  - http://github.com/app
  - http://itunes-link.co

Should the description be on its own line too?

**Comment by dkhamsing** [comment]
Might be better as part of a new repo structure where the readme is generated and the content resides in something like json..

**Comment by scribblemaniac** [comment]
I think that having the readme generated is an excellent idea! It allows the end format to easily be changed and allows for easier reading by programs.


Here is my proposal for a JSON structure, using the v2ex app as an example:
```
{
	title: "Open-Source iOS Apps",
	description: "A collaborative list of open-source iOS apps, your [contribution](https://github.com/dkhamsing/open-source-ios-apps/issues) [is](https://github.com/dkhamsing/open-source-ios-apps/pulls) [welcome](#contact) :smile:",
	categories: [
		{
			title: "News",
			id: "news"
		}
	],
	apps: [
		{
			title: "v2ex",
			category: "news",
			description: "An iOS client for the technical and creative website v2ex.com",
			lang: "zho",
			source: "https://github.com/singro/v2ex",
			homepage: "https://v2ex.com/",
			itunes: "https://itunes.apple.com/app/v2ex-chuang-yi-gong-zuo-zhe/id898181535",
			stars: 1497
		}
	]
}
```
There are two main types of objects here, the category object, which goes under categories, and the app object, which goes under apps. Here's the structure I was thinking of for each of them:

**Category object**
Required attributes: `title`, `id`
Optional attributes, with default value in parentheses: `description` (`""`)

**App object**
Required attributes: `title`, `category`, `description`, `source`
Optional attributes, with default value in parentheses: `lang` (`"eng"`), `homepage` (`null`), `itunes` (`null`), `stars` (`null`), `tags` (`[]`)
Notes:
- The tags attribute is for extra metadata for the app. For example a swift app would have `tags: ["swift"]`
- The lang attribute should be a [ISO 639-2 code](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes).

Let me know what you think, what you like and don't like. If you finalize a format, and it is easily parsable (JSON, XML, etc.), I will help convert the existing information to the new format. :smile:

**Comment by dkhamsing** [comment]
Thanks for your proposal

It looks pretty good

Another repo considering this is awesome-swift so it would be great if the format was compatible or generic. Maybe it can say projects instead of apps

Would you write a script to convert the markdown?

**Comment by scribblemaniac** [comment]
I finished the script yesterday and clean up the results today. A PR will be coming up right away.

For those of you who are curious, this is the script I used to convert the markdown to JSON. It handles most cases, and just throws warnings for the rare edge cases so they can easily be fixed manually.
[The converter script at JSFiddle](https://jsfiddle.net/scribblemaniac/2emovew5/14/)

[JSONLint](http://jsonlint.com/) was used for verification and formatting.

**Comment by dkhamsing** [comment]
@scribblemaniac nice script

**Comment by scribblemaniac** [comment]
@dkhamsing Thanks :blush:

**Comment by dkhamsing** [comment]
@scribblemaniac hope to merge your pull soon

**Comment by dkhamsing** [comment]
keep u posted
