### ISSUE TITLE
Move archive.md to data.json

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#282]
- [x] get `archive.md` data into `data.json`: add "archived" tag
- [x] ~~update schema~~
- [x] update convert.rb 
  - omit archived items
  - create archive.md
- [x] update deploy.sh
- [ ] test
- [ ]  update CONTRIBUTING about project deletion: To delete a project, add the value "archived" to the `tags` field
---

- unrelated, but the convert script should probably be in Swift 😢

**Comment by dkhamsing** [comment]
@scribblemaniac thinking of adding "archived" apps to contents.json.. would a new field called `archived` with Boolean as value work ?

**Comment by scribblemaniac** [comment]
@dkhamsing I was thinking of making it an `archived` tag instead. Either would work.

**Comment by dkhamsing** [comment]
Hm I like that, no change to schema!

**Comment by dkhamsing** [comment]
@scribblemaniac @kvnbautista 

To archive an app (no longer maintained or no longer working etc..), add the `tag` "archive" in contents.json

Thx
