### ISSUE TITLE
Updated contents json

### ISSUE THREAD

**Issue by Romi08** [dkhamsing/open-source-ios-apps#285]
I have added the json file as described in mail @dkhamsing, @kvnbautista.Thank u

**Comment by Romi08** [comment]
I have added the son file as described in mail @dkhamsing, @kvnbautista.Thank u

**Comment by dkhamsing** [comment]
?

**Comment by dkhamsing** [comment]
Please open a pull request

**Comment by Romi08** [comment]
yeah i have closed the issue and sent a pull request.

**Comment by dkhamsing** [comment]
Let me know if you need help

**Comment by Romi08** [comment]
I have removed the contents from readme and updated in contents.json is the
fine . shall i send a pull request now..

**Comment by dkhamsing** [comment]
Ok

Feel free to close and start over if that is easier

**Comment by dkhamsing** [comment]
Go here https://github.com/dkhamsing/open-source-ios-apps/blob/master/contents.json and click the edit button

Then add your entry, at the very end near the bottom 


Thx

**Comment by Romi08** [comment]
i guess i have given correct now.Sorry for the trouble.

**Comment by dkhamsing** [comment]
If you look here https://github.com/dkhamsing/open-source-ios-apps/pull/287 it still says the pull request cannot be merged 

![image](https://cloud.githubusercontent.com/assets/4723115/15205712/8dc7a1b8-17ce-11e6-99ba-cb40f82c08d8.jpeg)

Please follow my instructions https://github.com/dkhamsing/open-source-ios-apps/issues/285#issuecomment-218663834
