### ISSUE TITLE
Add emoji for Available in App Store

### ISSUE THREAD

**Issue by nloveladyallen** [dkhamsing/open-source-ios-apps#302]
I suggest 📲.

**Comment by dkhamsing** [comment]
Hm this is better than looking for the iTunes link??

**Comment by nloveladyallen** [comment]
IMO yes, just like the 🔥s are better than looking for a number of stars. (Of course, I am proposing this in addition to the iTunes link, not instead of it)

**Comment by dkhamsing** [comment]
Well the number of stars is a click away, but the iTunes link is just below 

Anyway will keep this open and see if anyone likes it too

Thx

**Comment by dkhamsing** [comment]
@nloveladyallen played with this and in the end, it looked lost in the noise because too many projects have itunes links 

Thanks for the suggestion!
