### ISSUE TITLE
Add this app (for Apple TV)

### ISSUE THREAD

**Issue by iAmRenzo** [dkhamsing/open-source-ios-apps#309]
UitzendingGemist; it's a Dutch app, therefor the description is Dutch @kvnbautista
https://github.com/4np/UitzendingGemist

```js
{
"title": "UitzendingGemist by 4np",
"category": "apple-tv",
"description": "Uitgebreide UitzendingGemist app voor Nederland",
"source": "https://github.com/4np/UitzendingGemist",
"tags": ["swift"]
}
```

**Comment by dkhamsing** [comment]
TODO: this requires updating the current UitzendingGemist app title to: UitzendingGemist by jeffkreeftmeijer

**Comment by iAmRenzo** [comment]
No!!
I this is a different app. Different developer.
Both work :)

**Comment by dkhamsing** [comment]
Yea I meant update existing entry..
Hey can you tell me what's the different between the two apps??

**Comment by iAmRenzo** [comment]
Ah ok. That's fine ;)

Yes. They serve the same purpose. But they are different in how they work.
I find my entry more useful. I know existing one works without updates (server side updates) so is easier.

**Comment by dkhamsing** [comment]
Ok thanks
