### ISSUE TITLE
README Format

### ISSUE THREAD

**Issue by jeffreyjackson** [dkhamsing/open-source-ios-apps#31]
Hey @dkhamsing - take a look at this [repo](http://github.com/pcqpcq/open-source-android-apps)

**Comment by dkhamsing** [comment]
Looks good, thanks

**Comment by dkhamsing** [comment]
I had started working on something but kinda gave up.. https://github.com/dkhamsing/open-source-ios-apps/blob/table/features.md what do you think

**Comment by jeffreyjackson** [comment]
looks good!  :beers: :grimacing:

**Comment by jeffreyjackson** [comment]
I'd probably leave off the language type since the repo shows that anyway, and would require upkeep on everyone's part to show that.

**Comment by dkhamsing** [comment]
I guess it's more about coming up with app categories..

**Comment by dkhamsing** [comment]
You know, while tables look great.. they are not so good to edit (or read in plain text). Will close for now but feel free to make a pull request :grin:
