### ISSUE TITLE
When is a project old/not maintained?

### ISSUE THREAD

**Issue by scribblemaniac** [dkhamsing/open-source-ios-apps#312]
It would be nice to have a clearer definition of old projects so we know exactly when they are ready to be put in the archive. In fact if we had a "X days without a commit" kind of definition, then in theory a script could go through the github links and check for outdated apps automatically.

**Comment by dkhamsing** [comment]
Time would be an indicator but basically we should archive projects that no longer build or that was not updated for current iOS - 2

There could be exceptions 

What do you think

**Comment by scribblemaniac** [comment]
I think that's fair. Certainly not all old applications are broken and not all new applications work. Could you put that somewhere in the CONTRIBUTING.md or on the wiki please?

**Comment by dkhamsing** [comment]
Will do

**Comment by dkhamsing** [comment]
Updated https://github.com/dkhamsing/open-source-ios-apps/wiki/Deleting

**Comment by scribblemaniac** [comment]
Good work, thanks!
