### ISSUE TITLE
Chaty

### ISSUE THREAD

**Issue by lfarah** [dkhamsing/open-source-ios-apps#313]
[Chaty](https://github.com/LunarFlash/Chaty) - Anonymous chat app leveraging Google's Firebase, a NoSQL backend and WebSocket for real time data synching

Is this app valid for *Open Source iOS Apps* even though it isn't on the App Store?

**Comment by lfarah** [comment]
+ maybe create a *Firebase* section?

**Comment by dkhamsing** [comment]
Looks ok to add, use category = communication

**Comment by dkhamsing** [comment]
Update: use `category = [ "firebase", "communication" ]`
