### ISSUE TITLE
Kodi

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#323]
@scribblemaniac hey for the main kodi entry https://github.com/dkhamsing/open-source-ios-apps/commit/07f6376bf66f0d5df737d26e341c5f7a2a0c8e0d

isn't that software you run on a computer?

**Comment by scribblemaniac** [comment]
They have versions for a ton of different platforms. They have a remote for iOS as well as an actual version of the media center for iOS (but this isn't on the app store for some reason, possibly hardware acceleration issues?). You can find some more details about their iOS platform here:

http://kodi.wiki/view/IOS

You can find compilation instructions for the iOS platform here:

https://github.com/xbmc/xbmc/blob/master/docs/README.ios

**Comment by dkhamsing** [comment]
Thx! That was a bit confusing

**Comment by dkhamsing** [comment]
Updating the `homepage` to http://kodi.wiki/view/IOS, I think that will be good
