### ISSUE TITLE
License check queue

### ISSUE THREAD

**Issue by scribblemaniac** [dkhamsing/open-source-ios-apps#326]
All of the apps that still need license tags. I will also try to add more homepages at the same time.

- [x] Artsy Shows
- [x] EX Player
- [ ] Provenance
- [x] UitzendingGemist by jeffkreeftmeijer
- [ ] WWDCTV
- [ ] BaiduFM-Swift
- [x] Bither
- [x] Brew
- [ ] Bus Today
- [ ] Calculator by noodlewerk
- [ ] Calculator by mukeshthawani
- [x] Cherry
- [x] Connectivity Demo
- [x] CoolSpot
- [x] Cortado
- [x] Done
- [x] FlickrWatch
- [x] GrandCentralBoard
- [ ] Gulps
- [ ] heartrate
- [x] HighStreet
- [ ] HN Reader
- [ ] Impulse
- [ ] KTPomodoro
- [ ] Lister
- [x] Natural Language Clock
- [x] OnTime
- [x] Parties for WWDC
- [ ] PhoneBattery
- [x] PhotoWatch
- [ ] Soon
- [x] WatchKit-Apps
- [ ] Watchman
- [ ] WatchNotes
- [x] watchOS-2-Sampler
- [x] WatchPics
- [ ] WatchSnake
- [ ] WatchStocks
- [x] Wunderschnell
- [x] Brave
- [ ] Endless Browser
- [x] Firefox
- [ ] Frameless
- [x] Actor
- [x] BLEMeshChat
- [ ] Chats
- [x] ChatSecure
- [ ] Colloquy
- [ ] IRCCloud
- [ ] M
- [x] Mumble
- [x] Rocket.Chat
- [ ] Signal
- [ ] surespot
- [ ] Telegram
- [x] TextEthan
- [x] EventBlankApp
- [ ] NortalTechDay
- [ ] ParseDeveloperDay
- [ ] RWDevCon
- [ ] trySwiftApp
- [x] Valio
- [ ] Adblock Fast
- [ ] Adblock Plus
- [x] BlockParty
- [x] Focus
- [x] AppLove
- [ ] Bequest
- [ ] Codinator
- [ ] Charter
- [ ] CI2Go
- [x] Review Time
- [ ] TLDR Man Page
- [x] wat
- [x] Github-Swift
- [ ] Monkey
- [x] MrCode
- [ ] OctoPodium
- [x] BitStore
- [x] breadwallet
- [ ] Buck Tracker
- [x] Coins
- [ ] Concurrency
- [x] doughwallet
- [x] Savings Assistant
- [ ] TodayStocks
- [ ] ToThePenny
- [ ] 翻翻看
- [x] 2048 in Objective-C
- [x] 2048 in Swift
- [ ] Bridges
- [ ] Canabalt
- [x] CardsAgainst
- [ ] Chess
- [x] CodeCombat
- [ ] Chuck
- [ ] DOOM
- [ ] DOOM-IOS2
- [ ] Dungeon Crawl
- [x] Five In A Row (五子棋)
- [ ] FlappySwift
- [x] Game Of Life
- [ ] GBA4iOS
- [ ] Gorillas
- [ ] GrubbyWorm
- [x] littlego
- [x] MUDRammer
- [x] Mission999
- [ ] Orbit7
- [ ] Sakura Fly
- [x] SceneKitFrogger
- [ ] Spare Parts
- [x] Stick-Hero-Swift
- [ ] Wolfenstein 3D
- [x] Arex
- [x] AsthmaHealth
- [x] Depressed
- [x] GlucoSuccess
- [ ] HealthKit~Swift
- [ ] Jim
- [ ] LogU
- [x] mPower
- [x] MyHeartCounts
- [ ] rTracker
- [x] Share The Journey
- [ ] Speak
- [ ] AA-Keyboard
- [ ] ClickWheelKeyboard
- [ ] Hodor
- [x] NaughtyKeyboard
- [ ] Slidden
- [x] Alarm
- [ ] Doppio
- [x] Cafe
- [ ] DoctorNearby
- [ ] EatNow
- [x] GeoTappy
- [ ] HopperBus
- [ ] iBeaconTasks
- [ ] Locative
- [x] Moves
- [x] OneBusAway
- [ ] OwnTracks
- [x] ParkenDD
- [ ] pathlogger
- [ ] PebCiti
- [x] Startups - Mapped In Israel
- [ ] Swift-Walk-Tracker
- [x] Smart Traveller (UberGuide)
- [ ] VisitBCN
- [x] 360 VR Player
- [ ] Analog Synth X
- [x] Artsy
- [x] Artsy Folio
- [ ] CollageMaker
- [ ] ColorBlur
- [x] ComicFlow
- [x] DoubanFM
- [x] Dunk
- [ ] Eleven
- [ ] Filterpedia
- [ ] Flickr-Search
- [ ] FreeStreamer
- [ ] KonaBot
- [x] Longboxed
- [ ] Megabite
- [ ] movies
- [ ] OCiney
- [x] OpenPics
- [x] Open Source Selfie Stick
- [ ] PhotoBrowser
- [x] Poppins
- [ ] PhishOD
- [ ] PopcornTime
- [ ] prankPro
- [ ] Pugs
- [x] Revolved
- [x] SoundCloudSwift
- [x] Swift ASCII Art Generator
- [x] Swifteroid
- [x] SwiftFlickrApp
- [x] Swift Radio Pro
- [ ] SwiftSpace
- [ ] TechTavta
- [ ] That Movie With
- [ ] Textbook
- [x] Upupu
- [ ] VLC
- [x] VoiceMemos
- [x] xkcd
- [ ] xkcd Open Source
- [ ] Designer News App
- [x] Feeds4U
- [x] GrinnellEvents
- [x] NirZhihuDaily2.0
- [x] Reddit
- [ ] RSSRead
- [x] TabDump
- [x] The Oakland Post
- [x] v2ex
- [ ] Hacker News Client
- [ ] HackerNews (Y)
- [x] HackerNews
- [ ] Hackers
- [ ] HN-App
- [x] News/YC
- [x] news
- [ ] Simple Reader
- [ ] Coding
- [ ] DuckDuckGo
- [ ] WhiteHouse
- [ ] Wikipedia
- [ ] WordPress
- [x] Cannonball
- [ ] Apple Developer Library
- [ ] Apple WWDC 2015
- [x] CloudKit in Objective-C
- [x] CloudKit in Swift
- [ ] Federal Data SDK
- [x] Furni
- [ ] HomeKit-Demo
- [x] iOS 8 Sampler
- [x] iOS 9 Sampler
- [ ] KnockToReact
- [x] Layer-Parse
- [x] LayerPlayer
- [x] LVMC
- [x] OpenShop.io
- [x] Polls
- [ ] Reusable Code
- [x] RKGist
- [ ] SafariAutoLoginTest
- [x] Starship
- [ ] StateRestorationDemo
- [ ] Swift-Demos
- [ ] FreeOTP Authenticator
- [x] MasterPassword
- [ ] MiniKeePass
- [ ] SkeletonKey
- [x] ZeroStore
- [ ] Aozora
- [ ] Peggsite
- [ ] StreetMusicMap
- [x] Yep
- [ ] 1Trackr
- [x] CloudKit-To-Do-List
- [x] MyAwesomeChecklist
- [ ] RealmToDo
- [ ] Swift Off
- [ ] Todo
- [ ] Todo.txt
- [x] Tinylog
- [x] Lucid Weather Clock
- [x] Pocket Forecast
- [ ] RainMan
- [x] Sol
- [x] SmileWeather
- [x] SwiftWeather
- [x] Tropos
- [ ] WeatherApp
- [ ] WeatherMap
- [ ] YoCelsius
- [x] PHPHub
- [ ] ProMonster
- [x] QiitaCollection
- [x] A Menjar
- [ ] bar
- [ ] Be my eyes
- [ ] BlogQuest
- [ ] Borrowed Books UFGRS
- [ ] CardDecks
- [x] ChineseZodiac
- [x] Colo
- [x] DeckRocket
- [x] EmotionNote
- [ ] GammaThingy
- [ ] GoodNight
- [x] GreatReader
- [ ] Hack Cancer
- [ ] Hidrate
- [x] iCopyPasta
- [x] iContactU
- [ ] iGrades
- [ ] Jupp
- [ ] LidderbuchApp
- [x] Mirror++
- [ ] my41
- [x] OpenCB
- [ ] Onions
- [ ] Open States
- [ ] ownCloud
- [x] Phonetic
- [ ] Population Clock
- [ ] Round & Split
- [x] Runner-Stats
- [ ] Swiflytics
- [x] Tether
- [x] Theseus
- [ ] TheReservist
- [x] TrollDrop
- [x] VPN On
- [x] Vinylogue
- [x] WaniKani
- [x] Words
- [ ] WWDC Students
- [ ] Yorkie
- [ ] ForceSketch
- [ ] Plum-O-Meter
- [ ] Malendar
- [x] Workdays
- [x] Edhita
- [x] SimpleMemo
- [x] SwiftNote
- [x] Coffee Timer
- [ ] Fojusi
- [x] TrackMyTime
- [x] Tracker 4 Compassion
- [x] DVD Collection Tracker
- [ ] Nested Lists
- [ ] Tasks
- [ ] Vegan Lists UK
- [ ] 2CITY
- [ ] Anypic in Objective-C
- [ ] Anypic in Swift
- [ ] AnyWall
- [x] how-much
- [ ] Parse-Challenge-App
- [ ] ParseStore
- [ ] Paws
- [x] allyoop
- [ ] 2048
- [ ] Movies
- [ ] TicTacToe
- [ ] UIExplorer
- [ ] Around Me
- [ ] Assemblies
- [x] Calculator
- [ ] Currency Converter
- [x] Den
- [x] Dribbble
- [ ] F8 2016
- [ ] Facebook Login
- [x] Finance
- [ ] Foreign Exchange
- [x] HackerNews-React-Native
- [x] Iceland Earthquakes
- [ ] iTunes Catalog Search
- [ ] london-react
- [ ] newswatch
- [ ] PocketNode
- [ ] Product Kitty
- [ ] Property Finder
- [ ] ReactNativeHackerNews
- [ ] RSS Reader
- [ ] Songkick
- [ ] Spacepics
- [ ] Sudoku
- [ ] To Do List
- [ ] Twitch
- [x] Weather
- [ ] BrewMobile
- [x] C-41
- [x] GitBucket
- [ ] GroceryList
- [x] HausClock
- [ ] ReactiveHackerNews
- [ ] ReactiveSwiftFlickrSearch
- [x] SimpleAuth
- [ ] SwiftRACGoogleImages
- [ ] GitHub API Client
- [x] Kiosk
- [ ] Contacts
- [x] Counter
- [ ] Rambler.Conferences
- [ ] To do
- [ ] Toggl Timer
- [ ] RealmVideo
- [ ] ReactiveKitten
- [ ] RailsCasts
- [ ] MetricTime
- [ ] AppSales-Mobile
- [ ] Bancha
- [x] Cheddar
- [x] Everest
- [ ] iOctocat
- [ ] LastFM
- [ ] Mume
- [ ] Pancake
- [ ] PocketFlix
- [x] Repo
- [x] SudokuResolv
- [ ] Vim
- [ ] wikiHow
- [ ] ActiveGS
- [ ] RetroArch
- [ ] MAME4iOS
- [x] DOSPad
- [ ] PPSSPP
- [x] Scary Flight
- [ ] MiamiSunglasses
- [ ] nds4ios
- [ ] iUAE
- [x] SwiftHub
- [ ] Balloon Burst
- [x] Closebox
- [x] Sentiments
- [x] TSWeChat
- [ ] Colorblind
- [x] UitzendingGemist by 4np
- [x] Fibonacc iClock
- [x] Chaty
- [x] iCook
- [x] Tweetometer
- [ ] Neverlate
- [x] Telemat-tvOS
- [ ] NumberPad
- [x] MAPS.ME
- [ ] Linphone
- [ ] Molecules
- [ ] Task Coach
- [ ] Castle Hassle
- [ ] Skeleton Key
- [ ] Cryptose
- [ ] Aeropack
- [ ] teh internets
- [ ] hoxChess
- [ ] iLabyrinth
- [ ] Heredox
- [ ] Pterodactyl Attack
- [x] Neocom for EVE Online
- [ ] Hostile Takeover
- [ ] XPilot
- [ ] AppSlate
- [ ] Authenticator
- [ ] CodeHub
- [ ] Dragon Shout App 2
- [ ] Frotz
- [x] Inkpad
- [ ] Wizard War
- [ ] ZBar Barcode Reader
- [x] Prey Anti Theft
- [ ] Prey Swift Client
- [ ] Radio Paradise
- [ ] Kodi
- [ ] Official Kodi Remote
- [x] Antidote
- [ ] Tutanota
- [x] Piwik Mobile 2
- [ ] Seafile Pro
- [x] OsmAnd Maps
- [x] Habitica
- [ ] MuPDF
- [ ] Kiwix
- [ ] Hedgewars
- [x] FreeRDP
- [ ] Minds Mobile App
- [x] Encryptr
- [ ] Spika
- [ ] Onion Browser
- [ ] projectM
- [x] openHAB
- [ ] LibreOffice Remote for Impress
- [ ] Free42
- [x] Miataru
- [ ] Wheelmap
- [ ] Ello

**Comment by dkhamsing** [comment]
You're doing this manually???

**Comment by scribblemaniac** [comment]
I'm currently making a script that should automate this for most github apps.

**Comment by scribblemaniac** [comment]
The script didn't work quite as well as I had hoped. Still, it took care of about half of them.

For the curious:
https://jsfiddle.net/scribblemaniac/nf2sxkaa/2/

**Comment by dkhamsing** [comment]
Cool

**Comment by dkhamsing** [comment]
I'll give it a go

**Comment by dkhamsing** [comment]
Script https://github.com/dkhamsing/open-source-ios-apps/commit/065fa8abbac33c3b335e95a7ff2500ddf1ab3c8c

**Comment by scribblemaniac** [comment]
As of ab3005b1a946d87d277aecfe088a431a8d0ff92c, all apps have licenses. Can we make this mandatory?

**Comment by scribblemaniac** [comment]
For all the data nerds out there, here are some graphs:
- [License Distribution](https://plot.ly/~scribblemaniac/1.embed)
- [Star Count by License](https://plot.ly/~scribblemaniac/3.embed)

**Comment by dkhamsing** [comment]
I'd rather not make it mandatory but can be at the discretion of the pull request review

**Comment by scribblemaniac** [comment]
Okay
