### ISSUE TITLE
New category: Clock

### ISSUE THREAD

**Issue by MichMich** [dkhamsing/open-source-ios-apps#339]
I'd like to add: https://github.com/MichMich/SwiftTextClock
Is it possible to add a `Clock` category?

**Comment by dkhamsing** [comment]
No clock category yet, maybe later

**Comment by dkhamsing** [comment]
@scribblemaniac should the timer category be renamed to clock?

**Comment by scribblemaniac** [comment]
It probably warrants a separate section since there are a few timer apps (measure duration) and a few clock apps (measure time of day).

**Comment by dkhamsing** [comment]
ok
