### ISSUE TITLE
Add not-in-appStore app to the Readme section

### ISSUE THREAD

**Issue by kostiakoval** [dkhamsing/open-source-ios-apps#35]
It's pretty hard to find those other app that aren't in the app store.

**Comment by dkhamsing** [comment]
True, I'll think about it

**Comment by dkhamsing** [comment]
This is the best I could come up with for now :smile:

**Comment by kostiakoval** [comment]
:+1: Looks good

**Comment by dkhamsing** [comment]
@kostiakoval hey the two lists were merged :grin:
