### ISSUE TITLE
Whats New

### ISSUE THREAD

**Issue by tinyhostingltd** [dkhamsing/open-source-ios-apps#360]
A what's new list would be great

**Comment by dkhamsing** [comment]
Meanwhile you could browse the commits https://github.com/dkhamsing/open-source-ios-apps/commits/master

**Comment by matteocrippa** [comment]
if we move w/ an app we can manage to use an APNS to notify user about news

**Comment by dkhamsing** [comment]
https://twitter.com/opensourceios
