### ISSUE TITLE
Themoji iOS App

### ISSUE THREAD

**Issue by KrauseFx** [dkhamsing/open-source-ios-apps#362]
I'd like to add [Themoji](https://github.com/themoji/ios) - A unique way to communicate with people around the world.

I can't decide what category to put it in, or if there should be an emoji category (I think it should 😄)

**Comment by dkhamsing** [comment]
Probbably "misc" for now 😉

**Comment by KrauseFx** [comment]
Thanks 🚀

**Comment by dkhamsing** [comment]
github needs big emojis 
🚀 🚀 🚀

**Comment by dkhamsing** [comment]
np :)

**Comment by KrauseFx** [comment]
Absolutely 👍
