### ISSUE TITLE
Use 'Added' instead of 'Add' in the commit message?

### ISSUE THREAD

**Issue by michieriffic** [dkhamsing/open-source-ios-apps#367]
Hi @dkhamsing,

I don't know if it's more appropriate to use 'Added' vs 'Add' on the commit title? 
'Add app-name by @github-username' -> 'Added app-name by @github-username'

Makes more sense grammatically?

**Comment by dkhamsing** [comment]
For brevity, we prefer "Add" at the moment
Thanks

**Comment by scribblemaniac** [comment]
Also I find that using verbs like this is a quite a common practice on Github. In fact, Pro Git recommends using the present impertive tense (https://git-scm.com/book/ch5-2.html):

> It’s also a good idea to use the imperative present tense in these messages. In other words, use commands. Instead of “I added tests for” or “Adding tests for,” use “Add tests for.”
