### ISSUE TITLE
Add Travel Category

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#368]
Can have at least these apps in there: themoji, uberguide..

Hmm how does it relate to the `location` category

**Comment by dkhamsing** [comment]
Also add School category?

**Comment by Aghassi** [comment]
If a travel category is added, can you please add my app? It is for NJ Transit commuters. https://github.com/findmybusnj/findmybusnj-swift

**Comment by dkhamsing** [comment]
will add it regardless, thank you!

**Comment by scribblemaniac** [comment]
I would be in favor of having an Education category instead of a school category, since it's a bit broader. Not sure about travel vs location though.

**Comment by dkhamsing** [comment]
@scribblemaniac thx, noted/updated

**Comment by matteocrippa** [comment]
My 2 cents, location is really wide, travel is for sure a subset of location.
Under there you can put transport (bus, metro) etc.

**Comment by dkhamsing** [comment]
ok
