### ISSUE TITLE
Swift marker update 

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#371]
Considering using `swift` or `Swift`  instead of 🔶
What do you think ?

@scribblemaniac @matteocrippa

**Comment by matteocrippa** [comment]
imho better, it would be really easy to use search to filter 👍

**Comment by scribblemaniac** [comment]
It's easier to tell at a glance with the icon, but it is also less intuitive. I don't have a strong opinion either way, but I would probably lean towards keeping the icon.

**Comment by dkhamsing** [comment]
preview
https://gist.github.com/anonymous/d3c31aaa197b750de25a0a5daedad120

![screen shot 2016-07-14 at 7 00 36 am](https://cloud.githubusercontent.com/assets/4723115/16842028/bbaf72a6-4990-11e6-95b6-e656a4fdbcbb.png)

![screen shot 2016-07-14 at 6 59 29 am](https://cloud.githubusercontent.com/assets/4723115/16841995/94d89856-4990-11e6-8098-1d07de7f88ba.png)

**Comment by dkhamsing** [comment]
you both bring good points, I think I will be switching
