### ISSUE TITLE
tvOS and watchOS

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#373]
Should tvOS and watchOS apps be removed from this list?

it can be argued that watchOS apps are pretty tied to iOS apps but not tvOS really...

@scribblemaniac @matteocrippa

**Comment by matteocrippa** [comment]
tvOS is not so far from iOS, watchOS is only a kinda extension, so I will keep both

**Comment by scribblemaniac** [comment]
I vote for keeping them since searching "open source watchOS apps" and "open source tvOS apps" both come up with this repo.

**Comment by dkhamsing** [comment]
thx guys
