### ISSUE TITLE
Add more <details>

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#387]
Add additional info in the README tucked under `<details>...</details>`

New supported fields:

- `screenshots`
- `date_added`

---

![details](https://cloud.githubusercontent.com/assets/4723115/17182298/da1b7e6e-53d7-11e6-88bb-8d37fead2410.gif)

Currently we can add the `license` when we generate the README  but `screenshots` and additional metadata is todo

New fields:

- `screenshots`
- `suggested_by`
- `date_added`

TODO

- [x] ~~update json schema~~ done in `history`
- [x] alternate syntax 
- [x] add license
- [x] do not show `suggested_by` 😞 
- [x] add screenshots to schema 
- [ ] How do future contributions update those fields ?
- [ ] Map names to GitHub users

**Comment by dkhamsing** [comment]
Alternate format will tuck in the details with the `source` link, looks cleaner 

![details](https://cloud.githubusercontent.com/assets/4723115/17183896/6b97ca90-53de-11e6-9e04-2b91d05239c0.png)

Need to move `homepage` into details though

**Comment by dkhamsing** [comment]
WIP https://github.com/dkhamsing/open-source-ios-apps/tree/details

**Comment by scribblemaniac** [comment]
It may be about time we migrated to generating an html page for github pages. Then we can get dynamic behavior such as expandable areas, search fields, and filters. I've been thinking about doing this for a while, but there hasn't been a pressing need for it until now. There will be way too much content if everything has all of these details.

**Comment by dkhamsing** [comment]
true this poor readme might choke

**Comment by scribblemaniac** [comment]
> true this poor readme might choke

To be honest, it might already be choking :wink:

**Comment by dkhamsing** [comment]
well without working on an actual webpage, this will be going in
