### ISSUE TITLE
can I translate this project to chinese language?

### ISSUE THREAD

**Issue by wg689** [dkhamsing/open-source-ios-apps#391]
this project is very good,but chinese developer English is not so well ,can I translate this project to chinese language? if I can I will tell other the translated project is from https://github.com/dkhamsing/open-source-ios-apps,I will write paper to tell other this project.  my Email:596201463@qq.com   /wg1@foxmail.com

**Comment by dkhamsing** [comment]
HI
Yes feel free to translate

A link back to here would be great
谢谢

**Comment by wg689** [comment]
A link back to here  must,thanks
