### ISSUE TITLE
XPilot

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#393]
7b5labs has been down since Aug 3

@scribblemaniac looks like the links we have for XPilot are down, can you find alternate links ?

**Comment by scribblemaniac** [comment]
Working on my vacation :sweat:

I did a bit of searching, but found no alternative links. I did find some contact information so I could do that if need be, or we could just go straight to archiving it. I'm pretty sure the app still works though. It doesn't hurt to at least try this:

@stealthboy Could you perhaps shed some light on what happened to 7b5labs.com and if an alternative place to access the source code for XPilot will be made available?

**Comment by dkhamsing** [comment]
@scribblemaniac oops sorry have a good vacation
