### ISSUE TITLE
Update header

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#398]
A collaborative list of open-source iOS, watchOS and tvOS apps, your [contribution](link here) is welcome 😄 

|Projects|Twitter|Updated|
|:---:   |:---:  |:---:|
|534     |[@opensourceios](https://twitter.com/)|August 8, 2016|

or 

![](https://img.shields.io/badge/Projects-534-green.svg?style=social) ![](https://img.shields.io/badge/Updated-Aug  8, 2016-green.svg?style=social) [![](https://img.shields.io/twitter/url/http/shields.io.svg?style=social&label=@opensourceios)](https://twitter.com/opensourceios) 

or

![](https://img.shields.io/badge/Projects-534-green.svg) [![](https://img.shields.io/badge/Twitter-@opensourceios-blue.svg)](https://twitter.com/opensourceios) ![](https://img.shields.io/badge/Updated-August  8,_2016-lightgrey.svg)

 
or

![](https://img.shields.io/badge/Projects-534-lightgrey.svg) [![](https://img.shields.io/badge/Twitter-@opensourceios-lightgrey.svg)](https://twitter.com/opensourceios) ![](https://img.shields.io/badge/Updated-August  8,_2016-lightgrey.svg)

**Comment by dkhamsing** [comment]
Bottom one is more compact

**Comment by dkhamsing** [comment]
Leaning towards the last option

**Comment by scribblemaniac** [comment]
I like having a bit of color, so I'm going to vote for the third one. I also think it might look better above the description than below it.

**Comment by dkhamsing** [comment]
Preview:

# Open-Source iOS Apps

A collaborative list of open-source iOS, watchOS and tvOS apps, your [contribution](link here) is welcome 😄 

![](https://img.shields.io/badge/Projects-534-green.svg) [![](https://img.shields.io/badge/Twitter-@opensourceios-blue.svg)](https://twitter.com/opensourceios) ![](https://img.shields.io/badge/Updated-August  8,_2016-lightgrey.svg)

or 
 
# Open-Source iOS Apps

![](https://img.shields.io/badge/Projects-534-green.svg) [![](https://img.shields.io/badge/Twitter-@opensourceios-blue.svg)](https://twitter.com/opensourceios) ![](https://img.shields.io/badge/Updated-August  8,_2016-lightgrey.svg)

A collaborative list of open-source iOS, watchOS and tvOS apps, your [contribution](link here) is welcome 😄

**Comment by dkhamsing** [comment]
I am thinking the first one..

**Comment by scribblemaniac** [comment]
I am fine with either.
