### ISSUE TITLE
Store project contents using YAML

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#399]
https://gist.github.com/anonymous/be788a5d82f40aedf29e8207f91e6b95 (using http://www.json2yaml.com/)

@scribblemaniac what do you think

**Comment by dkhamsing** [comment]
Note
- `@username` ❗ not valid yml string
- `"@username"` ✅

**Comment by scribblemaniac** [comment]
It looks a little bit better. The quoting thing could cause a bit of confusion for new contributors. Don't forget that all urls will have to be quoted as well then.

We would either have to find some alternative to the JSON Schema or abandon that kind of validation altogether.

YAML may be a bit easier for a regular person to read/edit, but I don't think it is enough to justify spending the time to change this.

**Comment by dkhamsing** [comment]
The format seems better

But yeah maybe not by that much
Closing for now
