### ISSUE TITLE
Webpage based readme

### ISSUE THREAD

**Issue by scribblemaniac** [dkhamsing/open-source-ios-apps#400]
WIP → https://dkhamsing.github.io/open-source-ios-apps/ by @scribblemaniac 🎉 

---

This is an extension of a suggestions made in #387.

The idea is that instead of just generating a README for this repository that has a formatted list of all of the OS Apps, a webpage on this project's Github Pages branch is created to display the apps. With the added flexibility of HTML, CSS, and Javascript, people will be able to interact with our content like never before. Filters, searches, expandable content, video demonstrations, better theming, you name it!

Obviously none of this will happen without work, so here is a very basic summary of what needs to be done:
- [x] Language flags
- [x] Theme switching (just swap the bootstrap stylesheets)
- [x] Improve tooltip display
- [x] Persistent settings
- [x] Screenshots
- [x] Parse markdown links
- [x] Fix internal links scrolling too far
- [x] Splash screen with loading bar
- [x] Fix links to users in "suggested by"
- [x] Background refresh
- [ ] Manual refresh
- [ ] Search
- [ ] Filtering
- [ ] Logo (see #413)
- [ ] Handle links in app descriptions
- [ ] Improve accessibility
- [ ] Sort order option
- [ ] Optimization
- [ ] Improve content (more tags, homepages, screenshots, etc. in the contents.json file)
- [ ] Filter out archived items
- [ ] Load projects for a particular `tag` (see #421)
- [ ] Screenshot thumbnails
- [ ] Refactor JS code
- [ ] Documentation
- [ ] Compress contents.json

If anyone with UX experience is reading this, we would love your help. I can help with the programming and content portions later this month.

@dkhamsing What is your position on this? Feel free to make improvements.

**Comment by dkhamsing** [comment]
Good idea, would love contributions

**Comment by IndyBob2019** [comment]
I would love to contribute, Im just getting my toe wet with html5 stuff so I probably wont be able to contribute much but I will keep my eye out for something that I think I can do. @dkhamsing  @scribblemaniac  is there already a git repository for this?

**Comment by scribblemaniac** [comment]
Okay, the first version is [live](https://dkhamsing.github.io/open-source-ios-apps/). I will work on it more next weekend. It's not quite ready yet, but I would love any feedback.

@IndyBob2019 Thanks for your interest! I have just added the code to the [gh-pages branch of this repository](https://github.com/dkhamsing/open-source-ios-apps/tree/gh-pages). You may find something that you can help with in the various TODOs scattered throughout the source right now.

**Comment by IndyBob2019** [comment]
Is there a way to clone this project? I got the clone link but it just downloaded the README for the whole project and a couple other unrelated files.

**Comment by dkhamsing** [comment]
Cloning should work, did you use the branch `gh-pages`

**Comment by IndyBob2019** [comment]
I don't know how to use branches lol, ill do some research and figure it out no worries.

**Comment by dkhamsing** [comment]
from the command line, should be `git checkout gh-pages`

**Comment by scribblemaniac** [comment]
Arghh! I wrote out this nice reply a week ago and forgot to hit the comment button! Well here it is for what it's worth:

> Okay, the first version is [live](https://dkhamsing.github.io/open-source-ios-apps/). I will work on it more next weekend. It's not quite ready yet, but I would love any feedback.

> @IndyBob2019 Thanks for your interest! I have just added the code to the [gh-pages branch of this repository](https://github.com/dkhamsing/open-source-ios-apps/tree/gh-pages). You may find something that you can help with in the various TODOs scattered throughout the source right now.

I will update the TODO list now that I have a better idea of what needs to be done.

**Comment by dkhamsing** [comment]
@scribblemaniac is there a better emoji to represent "download on appstore" because the iphone one makes it look like the project is for iphone

**Comment by scribblemaniac** [comment]
@dkhamsing [Download](http://fontawesome.io/icon/download/) or [Apple](http://fontawesome.io/icon/apple/) could work. Or we could just add the app store icon.

**Comment by dkhamsing** [comment]
yeah might as well? some version of 

![](http://assets.dockwa.com/assets/app-store-59a5d30dc366f66c1bcc556573b9f19b.png)

**Comment by scribblemaniac** [comment]
I'm effectively at the 1.0 release of the website now :tada: It doesn't have a lot of the bells and whistles yet (as you can tell from the todo list), but it has all the functionality of the README and then some. I would love some feedback at this point, so everyone please [check it out](https://dkhamsing.github.io/open-source-ios-apps/) and let me know what you think!

**Comment by dkhamsing** [comment]
Very exciting, thank you for all the work

**Comment by hblegg** [comment]
website looks good

**Comment by dkhamsing** [comment]
@scribblemaniac the theme switcher is pretty fancy
would it make sense to save on selection ?

**Comment by scribblemaniac** [comment]
@hblegg Thanks!

@dkhamsing Yeah, in hindsight that would be better. I'll change it soon.

**Comment by dkhamsing** [comment]
The site is looking good

Can we replace the stars by something else

Maybe just have: 152 ⭐️ 

I feel they convey the wrong idea at the moment, kinda like yelp star ratings

**Comment by dkhamsing** [comment]
@scribblemaniac ^

**Comment by scribblemaniac** [comment]
@dkhamsing Good idea, I will experiment with that soon.

P.S. You don't need to mention me every time 😉 I get notifications for everything in this project.

**Comment by dkhamsing** [comment]
Ok

**Comment by dkhamsing** [comment]
@scribblemaniac closing this for now for lack of activity :)

**Comment by scribblemaniac** [comment]
@dkhamsing Ok 😞 I will open it back up when I get the chance to continue working on this.

**Comment by dkhamsing** [comment]
No worries, thanks for your effort
