### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by matteocrippa** [dkhamsing/open-source-ios-apps#415]
iOS app is running a bit slow due to holiday season, btw we have at least an initial structure inherited by AwesomeSwift App.

If you have any feedback, idea or something else feel free to refer to this [repo](https://github.com/matteocrippa/awesomeSwift-iOS-App).

Refer to feature/newUI branch.

**Comment by dkhamsing** [comment]
Looks like a good start buddy
Let's have comments on https://github.com/matteocrippa/awesomeSwift-iOS-App if need be

Closing
