### ISSUE TITLE
Change Log?

### ISSUE THREAD

**Issue by wm-j-ray** [dkhamsing/open-source-ios-apps#418]
More of a feature request I guess. 

What is the best way to tell what new apps have been added?  Is there a change log?  

I like to check this repository on a regular basis, say once a week. What is the best way to figure out what has been added since the last time I checked other than diff'ing the repository?

Thanks in advance.

**Comment by scribblemaniac** [comment]
Our Twitter feed may be of some interest to you:
https://twitter.com/opensourceios

**Comment by dkhamsing** [comment]
#360
