### ISSUE TITLE
https://github.com/Kapeli/Dash-iOS

### ISSUE THREAD

**Issue by jeffreyjackson** [dkhamsing/open-source-ios-apps#448]
Hey man, I hope you're doing well.  Came across this...

**Comment by dkhamsing** [comment]
I'm good
Hope you are well too!

Thx!

**Comment by dkhamsing** [comment]
https://github.com/dkhamsing/open-source-ios-apps/commit/f0f3b84303f0e94f14c5436daf5fe09d02a75fb2
