### ISSUE TITLE
GH Pages

### ISSUE THREAD

**Issue by G2Jose** [dkhamsing/open-source-ios-apps#476]
Have you considered hosting this on Github pages? This looks like something that could really benefit from that. Should be fairly simple to have a script that consumes the json & creates a web page (possibly in react) with a clean searchable interface. 

https://pages.github.com/

**Comment by scribblemaniac** [comment]
We already use Github Pages, right here:
https://dkhamsing.github.io/open-source-ios-apps/

The website is not under active development because I'm too busy lately, but it should still be functional. For more details see here:
https://github.com/dkhamsing/open-source-ios-apps/issues/400

**Comment by G2Jose** [comment]
Sick!
