### ISSUE TITLE
App submitted

### ISSUE THREAD

**Issue by matteocrippa** [dkhamsing/open-source-ios-apps#507]
I update you about the official app, I have submitted that, but it was rejected for not too much contents... I make an appeal and let's cross our fingers. I do suppose the real cause is the name swift as it happened with awesome swift.

**Comment by Umity** [comment]
do we need to know this?

**Comment by matteocrippa** [comment]
@Umity it was only to keep update about the official app of open source iOS app repository, we managed to talk about that in the past during development and now that it is mature time for release I have only provided an update about the submission status.

For further details we are referring to this: https://github.com/matteocrippa/awesome-swift-ios

**Comment by Umity** [comment]
ok sorry, dont know why but getting way too much emails from github lately.

**Comment by dkhamsing** [comment]
Cool Matteo 
Keep m posted

**Comment by matteocrippa** [comment]
It's under a second review, at this first round it was notify that according `4.2.2` it doesn't provide so much native feature so it's a not-go for now. Let's see

**Comment by dkhamsing** [comment]
Closing, thanks
