### ISSUE TITLE
what about open-source-mac-apps repo?

### ISSUE THREAD

**Issue by jeffreyjackson** [dkhamsing/open-source-ios-apps#51]

**Comment by dkhamsing** [comment]
Very good point.. do you want to take it on?

**Comment by dkhamsing** [comment]
Also should link to https://github.com/pcqpcq/open-source-android-apps

**Comment by jeffreyjackson** [comment]
sure, what do you need from me?  want me to host the repo?

**Comment by dkhamsing** [comment]
Go for it

**Comment by jeffreyjackson** [comment]
i have a better idea... stay tuned.

**Comment by jeffreyjackson** [comment]
see here: https://github.com/AwesomeOpenSource/mac-apps

want to move these repos under an org and structure it that way?
