### ISSUE TITLE
Question about Already published apps on AppleStore

### ISSUE THREAD

**Issue by FCanaparro** [dkhamsing/open-source-ios-apps#518]
Hello.
When we publish on Apple Store we use our developer credentials, so, before publish on gitHub as 
public is there something to delete in particular?
I have some old apps, i was considering publish as public.
Not sure...
Have you guys done it?
Thanks

**Comment by dkhamsing** [comment]
Yea if you could remove any sensitive information, go for it.. developer id, api keys. If you are not sure, feel free to ask

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FCanaparro** [comment]
Well, exactly where should I look for?
 Plist?
Thanks for the answer

**Comment by dkhamsing** [comment]
Well you can find the developer id also in project settings .. do you use any third party services other than Apple? Fabric or some back end service 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Closing, feel free to ask questions again

**Comment by FCanaparro** [comment]
thanks
