### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#528]
@vpeschenkov hi Victor, would you be interested in being a collaborator on this project

Duties would mostly be around reviewing pull requests, fixing broken links, etc

Let me know 🙏

**Comment by vpeschenkov** [comment]
@dkhamsing Hi! Yes, I'm interested in it. Thank you for your trust!

**Comment by dkhamsing** [comment]
@vpeschenkov invited!
thank you for your time

let me know if you have any questions :)
