### ISSUE TITLE
Transfer to AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [dkhamsing/open-source-ios-apps#53]
https://github.com/AwesomeOpenSource

**Comment by jeffreyjackson** [comment]
hey @dkhamsing I made you an owner of that organization too

**Comment by jeffreyjackson** [comment]
Maybe we can persuade the android guy to move there also?

**Comment by dkhamsing** [comment]
Maybe :smile:

**Comment by jeffreyjackson** [comment]
I'm reaching out to people to make the move - let's see what happens.  I think its a smart move for all awesome repos.  We would be able to increase visibility for all projects, as well as increase the ability to contribute from all.

**Comment by dkhamsing** [comment]
Yeah.. the only thing I see is breaking of links although GitHub might take care of that with redirects. And then there's loss of ownership

Let's wait and see

**Comment by jeffreyjackson** [comment]
I think we should make whoever transfers over an admin/owner.  This way no one has less control that what they had to begin with.  Also, github handles redirects.

https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes

**Comment by dkhamsing** [comment]
Yeah but it's still single ownership vs org.. unless you go with permissions per repo
I dunno

**Comment by jeffreyjackson** [comment]
up to you, what makes the most sense?  we can manage it however we want to with the org

**Comment by pcqpcq** [comment]
Nice idea!

**Comment by jeffreyjackson** [comment]
hey @pcqpcq i just sent out your invites :smile: looking forward to working with you

**Comment by pcqpcq** [comment]
Done. I am in.
 I will check the transferring later

**Comment by jeffreyjackson** [comment]
Sounds great!  Looking forward to working with you

**Comment by pcqpcq** [comment]
1. I do think it is a good idea to do what we want with a organization.
2. I think the problem what @dkhamsing and I are concerning should be the same. In fact, I wonder what does @dkhamsing think?

**Comment by jeffreyjackson** [comment]
Instead of forking, let's create a list that point back to everyone else.
In the case that a repo becomes unsupported we can fork it at that time.

what do you think?  This should satisfy the majority of everyone's concern.

**Comment by dkhamsing** [comment]
Moved to https://github.com/pcqpcq/open-source-android-apps/issues/46
Thanks
