### ISSUE TITLE
Archive the apps updated before 2016

### ISSUE THREAD

**Issue by vpeschenkov** [dkhamsing/open-source-ios-apps#530]
@dkhamsing Hi! What do you think about archiving the apps updated **before 2016**? Because, lots of them are probably abandoned.

Also, [here](https://goo.gl/LDpRM8) is the list of apps (except the archived ones) sorted by the latest update year.

**Comment by dkhamsing** [comment]
Thanks for compiling this. Sounds good to me 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Can u take care of it ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpeschenkov** [comment]
Of course. I'll take care of it.
