### ISSUE TITLE
Remove Animoke

### ISSUE THREAD

**Issue by vpeschenkov** [dkhamsing/open-source-ios-apps#535]
@dkhamsing What do you think about this [project](https://github.com/BalestraPatrick/Animoke)? Can we remove it, because, it’s empty?

**Comment by dkhamsing** [comment]
it's empty? what do u mean

![screen shot 2018-01-15 at 2 46 04 pm](https://user-images.githubusercontent.com/4723115/34964522-dabf46b6-fa02-11e7-973b-fadaa09f78ae.png)

**Comment by vpeschenkov** [comment]
I mean this [AppDelegate.swift](https://github.com/BalestraPatrick/Animoke/blob/master/Animoke/AppDelegate.swift), [ViewController.swift](https://github.com/BalestraPatrick/Animoke/blob/master/Animoke/ViewController.swift). I couldn't find a code that do something.

**Comment by dkhamsing** [comment]
Ah thanks for this - yes let’s remove
🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
