### ISSUE TITLE
Update  projects 

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#539]
See the 404 found in 

https://github.com/dkhamsing/open-source-ios-apps/pull/538

**Comment by vpeschenkov** [comment]
@dkhamsing Hi! I have tried to check them but couldn't find anything.. What do you think about [this](https://github.com/dkhamsing/open-source-ios-apps/commit/f126e60bebad3230ccb5537925e077edf2cedc53)?

**Comment by dkhamsing** [comment]
what do u mean you couldn't find anything? your change look ok..

**Comment by dkhamsing** [comment]
could u also remove these


  1. [L169] 404 https://itunes.apple.com/app/lunchify/id1099214692  
  2. [L170] 404 https://itunes.apple.com/app/bat-loves-bugs/id969817533  
  3. [L173] 404 https://itunes.apple.com/app/space-zero/id1141164238  
  4. [L176] 404 https://itunes.apple.com/app/codesprint/id1148072754  
  5. [L188] 404 https://itunes.apple.com/app/terrarium/id891232736  
  6. [L198] 404 https://itunes.apple.com/app/token-wallet/id1200463445  
  7. [L217] 404 https://itunes.apple.com/app/fusecloud/id1173516856

**Comment by vpeschenkov** [comment]
@dkhamsing I meant that I was hoping to find a few new links instead of existing ones. But, I couldn't find any new links.

**Comment by dkhamsing** [comment]
Oh yea I think they were removed but thanks for looking 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
