### ISSUE TITLE
Ooops - readd objc in tags for these projects

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#547]
See https://github.com/dkhamsing/open-source-ios-apps/commit/ce754047bf922a9cfcd26c413f7df4e8c8e2a11d for complete list - around 200 projects

Continues #526

**Comment by vpeschenkov** [comment]
I'm fixing this today

**Comment by vpeschenkov** [comment]
Done in #549

**Comment by dkhamsing** [comment]
Wow amazing - thank you Victor 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpeschenkov** [comment]
@dkhamsing not a problem 😀
