### ISSUE TITLE
Shopping Category

### ISSUE THREAD

**Issue by SirArkimedes** [dkhamsing/open-source-ios-apps#555]
Proposal to add a category that matches App Store's category of `shopping`. This could contain apps similar to letgo, Wish, and Mercari to name a few (Popular ones listed, not sure which are open source, if any). I am also able to contribute an app to this category!

**Comment by kammerdiener** [comment]
I would agree with this. It could potentially help to encourage more apps to become open source! There doesn't seem like another category that this could fall into easily.

**Comment by dkhamsing** [comment]
Sounds good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
