### ISSUE TITLE
Which kind of the categories corresponds to SUSI.AI?

### ISSUE THREAD

**Issue by vpeschenkov** [dkhamsing/open-source-ios-apps#557]
[SUSI.AI](https://github.com/fossasia/susi_iOS) - Your Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots.

**Comment by dkhamsing** [comment]
If u can’t find something, you can use misc

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vpeschenkov** [comment]
thanks!
