### ISSUE TITLE
https://chat.susi.ai/overview

### ISSUE THREAD

**Issue by vpeschenkov** [dkhamsing/open-source-ios-apps#572]
@dkhamsing Hi there! I don't know what to do with that url. It works well in browser, however, we have the next warning. 
![Alt text](https://monosnap.com/file/wWhCCb5RspU12yVVaB4star8qHmPdn.png)
Should I add it to whitelist?

**Comment by dkhamsing** [comment]
Yes pls!

**Comment by dkhamsing** [comment]
thx @vpeschenkov
