### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by vpeschenkov** [dkhamsing/open-source-ios-apps#581]
#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
6 | [301](https://httpstatuses.com/301) | https://github.com/jasarien/Provenance redirects to<br>https://github.com/Provenance-Emu/Provenance
7 | [301](https://httpstatuses.com/301) | http://jamesaddyman.com/provenance/screenshots/provenance1.png redirects to<br>https://jamesaddyman.com/provenance/screenshots/provenance1.png
8 | [301](https://httpstatuses.com/301) | http://jamesaddyman.com/provenance/screenshots/provenance6.png redirects to<br>https://jamesaddyman.com/provenance/screenshots/provenance6.png
1276 | [301](https://httpstatuses.com/301) | https://github.com/tananaev/traccar-client-ios redirects to<br>https://github.com/traccar/traccar-client-ios
1278 | [301](https://httpstatuses.com/301) | https://github.com/tananaev/traccar-manager-ios redirects to<br>https://github.com/traccar/traccar-manager-ios

**Comment by dkhamsing** [comment]
Thx man!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
