### ISSUE TITLE
Add open-source-ios-apps to reactnative.gallery 🎨

### ISSUE THREAD

**Issue by xcarpentier** [dkhamsing/open-source-ios-apps#590]
Hi @dkhamsing!

Sorry, this is not an issue...

I'm Xavier and I’ve been working as a freelance React Native developer for more than 2 years.
I try to help community when I can: sharing my works on open-source, like you do!
But it's hard to be visible sometimes! Right?

I want to help developers to have more visibility.
So, I've created a website where developers can share with entire
world their React Native projects, components, apps...

This website allow developers to show their works and get feedback.
Just like a Dribbble but for React Native developers.

https://reactnative.gallery

**Comment by dkhamsing** [comment]
Hey there, sounds good but gonna close this :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
