### ISSUE TITLE
Onions and News/YC

### ISSUE THREAD

**Issue by bennyguitar** [dkhamsing/open-source-ios-apps#6]
**Onions**

An open-source, cloud encrypted text storage app that leverages client-side encryption instead of server-side encryption to make sure your stuff stays private.

* https://github.com/onionsapp/Onions-iOS
* https://onionsapp.github.io

**News/YC**

A beautiful open-source Hacker News client written in Swift - with user management, commenting, submitting and themes.

* https://github.com/bennyguitar/News-YC---iPhone
* https://github.com/bennyguitar/libHN - The modular HN library

**Comment by dkhamsing** [comment]
Thanks @bennyguitar 
Will add em

**Comment by bennyguitar** [comment]
Awesome thanks. I just realized I forgot the app store links:

* News/YC: https://itunes.apple.com/us/app/news-yc/id592893508?mt=8
* Onions: https://itunes.apple.com/us/app/onions/id687296481?mt=8

**Comment by dkhamsing** [comment]
:+1:
