### ISSUE TITLE
Add SnowHaze - Privacy Browser

### ISSUE THREAD

**Issue by n0bodyBod** [dkhamsing/open-source-ios-apps#604]
[SnowHaze](https://github.com/snowhaze/SnowHaze-iOS) by Illotros GmbH: https://itunes.apple.com/us/app/snowhaze/id1121026941?mt=8

**Comment by vpeschenkov** [comment]
@n0bodyBod Done. Thank you!

**Comment by n0bodyBod** [comment]
Happy to help :)
