### ISSUE TITLE
Instabug sponsorship 

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#606]
End sponsorship by removing changes in #595 May 23

**Comment by dkhamsing** [comment]
Hey @vpeschenkov created this for us to remember, coming up in a few days

**Comment by dkhamsing** [comment]
Oops looks like it can no longer be reverted .. should be easy though.. will create something new

**Comment by vpeschenkov** [comment]
Yea, I remember. If it can't be reverted, it'll be removed)

**Comment by dkhamsing** [comment]
Thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
