### ISSUE TITLE
Replace fire symbol 🔥

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#612]
In #585 it was alluded that the flags were a visual clutter.. maybe we can rethink the current use of 🔥 to denote projects on GitHub with many stars.. 

In fact, maybe we should use one of the following instead

★ 
☆

cc @vpeschenkov 

---

Please participate in the "poll" below (vote with 👍)

**Comment by dkhamsing** [comment]
🔥 is fine

**Comment by dkhamsing** [comment]
Use ★

**Comment by dkhamsing** [comment]
Use ☆

**Comment by scribblemaniac** [comment]
Use ⭐

**Comment by scribblemaniac** [comment]
Use 🌟
