### ISSUE TITLE
Automatic loading of screenshots

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#614]
In #585 it was revealed this page takes over 300MB to load .. 😅 

Let’s remove the embedding of screenshots

**Comment by dkhamsing** [comment]
cc @vpeschenkov

**Comment by dkhamsing** [comment]
Maybe as a first step, limit to one screenshot and profile how that’s like

**Comment by dkhamsing** [comment]
I think we'll replace images by links, sad but seems necessary

**Comment by dkhamsing** [comment]
@vpeschenkov done

**Comment by vpeschenkov** [comment]
Well done! The list looks awesome, takes to load only 2MB and seems like not our at the first sight 😄
