### ISSUE TITLE
Add Flappy Fly-Bird SpriteKit game 

### ISSUE THREAD

**Issue by jVirus** [dkhamsing/open-source-ios-apps#637]
Hello, 

Please add the following SpriteKit-based game:  https://github.com/jVirus/flappy-fly-bird

Description:
"An iOS/SpriteKit game that mimics Flappy Bird, but with addition of gameplay and graphics improvements"

Stars: 5

Thank you

**Comment by vpeschenkov** [comment]
@jVirus done, thank you!
