### ISSUE TITLE
Request open source app

### ISSUE THREAD

**Issue by SamboVisal** [dkhamsing/open-source-ios-apps#645]
I really like this blog. But i cannot find my desire app which called **Contact.**  Because i want to create a sample app which similar to contact app. I have been searching for a few days but nothing found. The reason i want to that app because i want to make sure when user add new input. I want that data display in specific section like user input name that starts with A then that name should be saved in A section and so on... I wonder how can i achieve something like this?

Thank for your help.

**Comment by dkhamsing** [comment]
Hi there, not sure we can help you here. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
