### ISSUE TITLE
An Open Source iOS App for Open Source iOS Apps

### ISSUE THREAD

**Issue by ethanhuang13** [dkhamsing/open-source-ios-apps#648]
Is there an app for this project? 
If not, I would like to create a simple one, that grabs contents.json and:

- List all apps
- Filter by category or keyword (search)
- Show detail (license, screenshots...)
- Link to App Store if applicable
- Link to project and author
- Others

Thoughts?

**Comment by dkhamsing** [comment]
There is https://github.com/dkhamsing/osia but feel free to write a much better one 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ethanhuang13** [comment]
Cool. If I do and submit to App Store, do you mind I take the name Osia? It's kinda hard to think of a better name 😂

**Comment by dkhamsing** [comment]
Yup go for it - closing this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
