### ISSUE TITLE
Extra empty lines in Developer, Browser sections

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#666]
Must be something in th convert script 😅

**Comment by vpeschenkov** [comment]
Do you mean this?
![](https://i.imgur.com/ko4Odml.png)
If yes, probably, it's because those items don't have screenshots.

**Comment by vpeschenkov** [comment]
This probably shouldn't be here if there are no screenshots:
![](https://monosnap.com/image/u4vCDEg5T4QWpE8Qj9AenKzAmaIjzG.png)

I can check this option a bit later.
