### ISSUE TITLE
Create one more list, organized by date added

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#737]
We have README, ARCHIVE - what if we had one more list called LATEST which would show the list, organized from new to old — simply showing latest 15 entries should be fine. 

~~Maybe it does not have to contain entire list (top 10, 20, 50?)~~

Thoughts? 

cc @vpeschenkov

**Comment by vpeschenkov** [comment]
Yes, it would be nice! 

> Maybe it does not have to contain entire list (top 10, 20, 50?)

I think 15 apps should be enough. New apps don't come very often (just 6 new apps have been added for the last 30 days).

**Comment by vpeschenkov** [comment]
I'm going to take care of it this week. I think it would be nice to do at least the following things:
- Add `LATEST.md` with the limit of 15 entities
- Refactor the script a bit - make the headers and footers to be more identical.

**Comment by scribblemaniac** [comment]
Just my two cents in the matter, I think it would be better if the latest document displayed all apps added in the last n days (30 maybe?) or something like that so that all new apps are on there a while, even if a lot of apps happen to be added at once.

**Comment by vpeschenkov** [comment]
> Just my two cents in the matter, I think it would be better if the latest document displayed all apps added in the last n days (30 maybe?) or something like that so that all new apps are on there a while, even if a lot of apps happen to be added at once.

Your idea is good. I just worry that in this case there will be a very small amount of apps. Perhaps, it will be good to show all apps for the last `n` days, and if the amount of them is too small (3-5) - add more apps to reach 15 apps.

**Comment by dkhamsing** [comment]
@vpeschenkov noting a change has to be made in this also https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/deploy.sh

**Comment by vpeschenkov** [comment]
Does it fit? ([LATEST.md](https://github.com/vpeschenkov/open-source-ios-apps/blob/feature/latest-list/LATEST.md))

**Comment by dkhamsing** [comment]
Looking good. 

Small request: 
Can we change 
> Shows the latest projects that are being added to the main list.

to
> Shows the latest projects that were added to the main list.

**Comment by dkhamsing** [comment]
@vpeschenkov @scribblemaniac could we make it simple to show latest 15 for now.. see how it goes and improve if necessary

**Comment by vpeschenkov** [comment]
> Can we change

[Done](https://github.com/vpeschenkov/open-source-ios-apps/blob/feature/latest-list/LATEST.md)

> could we make it simple to show latest 15 for now.. see how it goes and improve if necessary

What do you mean? It shows 15 apps at least or as many apps as were added for the recent 60 days:

```
  apps = source["projects"]
    .map { |app| App.new(app) }
    .select { |app| app.date_added != nil }
    .sort_by { |app| DateTime.parse(app.date_added) }
    .reverse
  
  latest_apps = apps.select { |app| (DateTime.now - NUMBER_OF_LATEST_DAYS) <= DateTime.parse(app.date_added) }

  # To make sure that there are always 15 apps at least.
  # If there are more than 15 apps for a given period of time, show them all, 
  # otherwise, add a few older apps to reach 15 apps on the list.
  if latest_apps.count < MINIMUM_LATEST_APPS_COUNT
    apps[latest_apps.count..MINIMUM_LATEST_APPS_COUNT - 1].each { |app| latest_apps << app }
  end
```

**Comment by dkhamsing** [comment]
I was thinking let's not look at dates - just last 15 apps added.

**Comment by vpeschenkov** [comment]
> I was thinking let's not look at dates - just last 15 apps added.

@dkhamsing updated the script
