### ISSUE TITLE
Apps to add

### ISSUE THREAD

**Issue by th3m** [dkhamsing/open-source-ios-apps#849]
- [x] session
- [x] raivo otp
- [x] jitsi
- [x] amaroq
- [x] mast

{
            "title": "Session",
            "category-ids": ["Communication"],
            "description": "Session is an end-to-end encrypted messenger that removes sensitive metadata collection.",
            "source": "https://github.com/loki-project/session-ios",
            "itunes": "https://apps.apple.com/app/session-private-messenger/id1470168868",
}
{
            "title": "Raivo OTP",
            "category-ids": ["Security"],
            "description": "A native, lightweight and secure time-based (TOTP) & counter-based (HOTP) password client.",
            "source": "https://github.com/raivo-otp/ios-application",
            "itunes": "https://apps.apple.com/us/app/raivo-otp/id1459042137",
}
{
            "title": "Jitsi Meet",
            "category-ids": ["Communication"],
            "description": "Secure, Simple and Scalable Video Conferences.",
            "source": "https://github.com/jitsi/jitsi-meet",
            "itunes": "https://apps.apple.com/us/app/jitsi-meet/id1165103905",
}
{
            "title": "Amaroq",
            "category-ids": ["Mastodon"],
            "description": "A floofy Mastodon companion.",
            "source": "https://github.com/ReticentJohn/Amaroq",
            "itunes": "https://apps.apple.com/us/app/amaroq-for-mastodon/id1214116200",
}
{
            "title": "Mast",
            "category-ids": ["Mastodon"],
            "description": "A beautiful Mastodon app.",
            "source": "https://github.com/ShihabM/Mast",
            "itunes": "https://apps.apple.com/us/app/mast/id1437429129#?platform=iphone",
}

**Comment by dkhamsing** [comment]
Thanks!
