### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by fulldecent** [dkhamsing/open-source-ios-apps#865]
I am open sourcing these apps, from the simple to complicated. And these include revenue-generating apps on the App Store.

https://github.com/fulldecent/formant-analyzer

https://github.com/fulldecent/8-ball

https://github.com/fulldecent/pizzaman

Please let me know if these meet the requirements.

**Comment by dkhamsing** [comment]
Thanks @fulldecent 🙏 Will take a look soon.
