### ISSUE TITLE
Files link does not work

### ISSUE THREAD

**Issue by chmac** [dkhamsing/open-source-ios-apps#870]
The Files link doesn't work on the homepage, it links to the "file list" at the top of the page. See https://github.com/dkhamsing/open-source-ios-apps#files

It does work on the /readme page, see https://github.com/dkhamsing/open-source-ios-apps/blob/master/README.md#files

I was going to submit a PR but I realise that the readme is being generated from code, so not sure how you'd fix it. My thought was to change `Files` into `Files_`.

**Comment by dkhamsing** [comment]
Thx for the report, will investigate

**Comment by dkhamsing** [comment]
Works in GitHub app 😅 ![image](https://user-images.githubusercontent.com/4723115/88927513-6437e480-d22c-11ea-9a02-0cf27297a910.gif)

Do you know why this is an issue for the files anchor?

**Comment by chmac** [comment]
@dkhamsing There are 2 files anchors. The first is files section of the UI.

<img width="915" alt="Screenshot 2020-07-30 at 15 26 04" src="https://user-images.githubusercontent.com/690997/88928397-14333f00-d279-11ea-9c4a-3fd87245bee3.png">

It's really a bug on GitHub's side, as they could have some list of existing anchors which are outside of markdown files and then rename those somehow.

**Comment by dkhamsing** [comment]
Sounds like the category should be renamed.. ok

**Comment by chmac** [comment]
@dkhamsing Maybe "File Management" would work?

**Comment by dkhamsing** [comment]
That would work.. anything shorter?

**Comment by dkhamsing** [comment]
Might try `File` singular

**Comment by dkhamsing** [comment]
Renamed to File, should work now.
