### ISSUE TITLE
Add the URL to the repo settings?

### ISSUE THREAD

**Issue by chmac** [dkhamsing/open-source-ios-apps#881]
Following up from #871, would you be open to adding the project URL to the repo settings so that it appears in the top right part of the GitHub listing?

I think this would make it much more obvious to folks that they can click there to load it.

**Comment by dkhamsing** [comment]
Can you add a screenshot example ? Thx

**Comment by chmac** [comment]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/690997/92497883-34e8a000-f1fa-11ea-808b-25701fef7184.png">

If you click this gear icon in the top right you can edit the description, then you can edit the 2nd field down, called Website.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/690997/92497948-4a5dca00-f1fa-11ea-9aae-13aa4e089455.png">

I think it makes the link a lot more visible to folks browsing the site.

**Comment by dkhamsing** [comment]
Ah thanks! Sorry didn't understand what you meant at first.

**Comment by dkhamsing** [comment]
Should be done

**Comment by dkhamsing** [comment]
@chmac I've changed the url to: https://open-source-ios-apps.netlify.app
