### ISSUE TITLE
Apps that use Core Data

### ISSUE THREAD

**Issue by kevinnguy** [dkhamsing/open-source-ios-apps#89]
Hi everyone, I was wondering if any of you guys know of any open sourced iOS apps that utilizes Core Data. I'm learning how to use Core Data and would like to learn its best practices. Thanks!

P.S. sorry if making an issue is inappropriate. Figured this would be the best way to ask a question. Thanks for your hard work @dkhamsing!

**Comment by dkhamsing** [comment]
Hey @kevinnguy, it is a good question

Here are some examples
- https://developer.apple.com/library/ios/samplecode/iPhoneCoreDataRecipes/Introduction/Intro.html
- https://developer.apple.com/library/ios/samplecode/CoreDataBooks/Introduction/Intro.html
- http://www.objc.io/issues/4-core-data/full-core-data-application/
- http://www.raywenderlich.com/85578/first-core-data-app-using-swift :large_orange_diamond: 


I will see about adding a Core Data section

**Comment by kevinnguy** [comment]
Thanks for the response @dkhamsing!
