### ISSUE TITLE
Is there no email app like k9

### ISSUE THREAD

**Issue by severus-tux** [dkhamsing/open-source-ios-apps#894]
Hi, I surprised to see that there is no opensource email app on ios. I am not talking about email *services*. Just a generic email client which can be configured to use with any IMAP/SMTP server. On android there is [K9](https://k9mail.app/), [FairEmail](https://email.faircode.eu/), etc... On Linux and Windows there is [Thunderbird](https://www.thunderbird.net/en-GB/), [Evolution](https://en.wikipedia.org/wiki/GNOME_Evolution) etc.. What alternatives are there on iOS? (of course opensource alternatives)

**Comment by dkhamsing** [comment]
@severus-tux looks like you are correct, there is no such app for IMAP / SMTP on this list - hope that can change in the future

**Comment by dkhamsing** [comment]
@severus-tux how about these?
- https://github.com/mehulparmar4ever/DemSMTP-MailCore-Example-iOS
- https://github.com/110440/TTEmail

**Comment by acmpo6ou** [comment]
Sadly they don't look maintained.
