### ISSUE TITLE
Duplicates on the web build

### ISSUE THREAD

**Issue by chmac** [dkhamsing/open-source-ios-apps#903]
See [this page](https://open-source-ios-apps.netlify.app/category/tasks/) for an example. Notice the duplicated RSToDoList entry. It's not duplicated in the source json so it must be something in the gatsby setup. Unclear how / why. Will look into it when I have some time.

@dkhamsing I'm not a contributor here so I can't assign this to myself or tag it as a bug, don't know if you can do that either if I'm not a contributor. Maybe somebody else will also find and fix the issue.

**Comment by chmac** [comment]
@dkhamsing I had a look at this today, but I can't reproduce it locally. I've also tried a build on netlify, and it doesn't reproduce there. Can you try logging into netlify and going to the site then the Deploys screen and then there's a dropdown Trigger Deploy, choose the Clear cache and deploy site option.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/690997/99656332-0a6a5d00-2a5d-11eb-85dd-837e7de7a242.png">

Maybe that will fix the issue. Unclear what caused it or why it's happening on the live build...

**Comment by dkhamsing** [comment]
@chmac done

this page is looking good
https://open-source-ios-apps.netlify.app/category/tasks/

Before and after
![Screen Shot 2020-11-19 at 8 35 14 AM](https://user-images.githubusercontent.com/4723115/99695276-3f1ceb00-2a42-11eb-872e-2e4945f9cd7a.png)

**Comment by chmac** [comment]
@dkhamsing Awesome, then at least we solved it. Hopefully we don't have the issue again. Otherwise there's probably a way to reduce caching in netlify, but for now, I'll assume it's solved.

**Comment by kosaimgmg2021** [comment]
🍸

**Comment by philipturner** [comment]
The duplication bug is still happening in September 2021. A new issue has been created about this.

**Comment by dkhamsing** [comment]
I kicked off a clear cache + redeploy 🙏
