### ISSUE TITLE
Categorize projects - Consider adding the last active date of any project

### ISSUE THREAD

**Issue by tejuamirthi** [dkhamsing/open-source-ios-apps#930]
Hi,
I'm just one other developer looking forward to contributing for the open-source community. This project has helped many people like me in a lot of ways. So I'd like to thank everyone who helped to achieve this.

So, is there any way to categorize the active projects or atleast see the most recent `active` date of the project. As there are many projects listed, sometimes it's hard to even realise, some repos are no longer maintained(I do agree that even those repos are great, maintained for so long and archived may be). I do feel it will give everyone a better overview. May be this could be a project in itself(just saying :-P). Or may be an over ambitious idea but please, people with scripting knowledge, can we have a script to display the recent active date along with the name of the project?

I'm sorry, if this already exists. Please let me know and close the issue. I couldn't find, so creating one.

**Comment by dkhamsing** [comment]
@tejuamirthi displaying the last active date is not possible today, but it is a great idea. 

There is a script that runs monthly to update the stars: https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/osia_update_stars.rb

It could be updated to get this information
https://docs.github.com/en/rest/reference/repos#get-a-repository

```
"updated_at": "2011-01-26T19:14:43Z",
```

**Comment by dkhamsing** [comment]
This issue is addressed in #931, thank you!
