### ISSUE TITLE
Truncated README

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/open-source-ios-apps#933]
It appears GitHub now clips/trims the README when you visit the repo: https://github.com/dkhamsing/open-source-ios-apps

**Comment by vpeschenkov** [comment]
What do you think if just replace it by something like this:

# Open-Source iOS Apps

A collaborative list of open-source `iOS`, `iPadOS`, `watchOS` and `tvOS` apps, your [contribution](https://github.com/dkhamsing/open-source-ios-apps/blob/master/.github/CONTRIBUTING.md) is welcome (project [website](https://open-source-ios-apps.netlify.app)) :smile:

![](https://img.shields.io/badge/Updated-February%2028,%202021-lightgrey.svg)

- [All projects ({count})](https://github.com/dkhamsing/open-source-ios-apps/blob/master/README.md) 
- [Latest projects ({count})](https://github.com/dkhamsing/open-source-ios-apps/blob/master/LATEST.md) 
- [App Store projects ({count})](https://github.com/dkhamsing/open-source-ios-apps/blob/master/APPSTORE.md) 
- [Archived projects ({count})](https://github.com/dkhamsing/open-source-ios-apps/blob/master/ARCHIVE.md) 

## Thanks

This list was inspired by [awesome-ios](https://github.com/vsouza/awesome-ios) and [awesome-swift](https://github.com/matteocrippa/awesome-swift). Thanks to all the [contributors](https://github.com/dkhamsing/open-source-ios-apps/graphs/contributors) 🎉 

## Contact

- [github.com/dkhamsing](https://github.com/dkhamsing)
- [twitter.com/dkhamsing](https://twitter.com/dkhamsing)

**Comment by dkhamsing** [comment]
@vpeschenkov lookin good

We could also move the project website link from the intro line to the new section at the bottom

- [All projects ({count})](todo)
- ..
- [Archived projects ({count})](todo)
- [Project website](todo)

**Comment by dkhamsing** [comment]
This issue is no longer an issue.
